module.exports = [
	{
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "commonjs",
			globals: {
				Module: "readonly",
				MMMECCountdown: "readonly",
				document: "readonly",
				window: "readonly",
				localStorage: "readonly",
				setInterval: "readonly",
				clearInterval: "readonly",
				setTimeout: "readonly",
				clearTimeout: "readonly",
				fetch: "readonly",
				AbortController: "readonly",
				Date: "readonly",
				Math: "readonly",
				Number: "readonly",
				String: "readonly",
				Array: "readonly",
				Object: "readonly",
				console: "readonly",
				process: "readonly",
				require: "readonly",
				module: "readonly",
				exports: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
			},
		},
		rules: {
			"no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
			"no-undef": "error",
		},
	},
	{
		ignores: ["node_modules/**"],
	},
];
